### ISSUE TITLE
no vmlinuz in syslinux/ while applying kernel

### ISSUE THREAD

**Issue by KenMizz** [kitakar5525/chromeos-kernel-linux-surface#19]
the only vmlinuz i found is under /boot with two vmlinuz files ``vmlinuz`` and ``vmlinuz-4.14.157``

I'm using Kernel version: ``chromeos-v5.4.39.r4076.d37238f2773c3-surface-brunch``

**Comment by kitakar5525** [comment]
Hi, I guess those `vmlinuz` and `vmlinuz-4.14.157` are from chromeos image, which are in `ROOT-A/boot`.

When you extract the binary release `chromeos-v5.4.39.r4076.d37238f2773c3-surface-brunch`, you'll see `vmlinuz-5.4.39-g0817b280da6c` in boot directory.
```bash
$ tree  
.
└── chromeos-v5.4.39.r4076.d37238f2773c3-surface-brunch
    └── chromeos-kernel-linux-surface-5.4.39-g0817b280da6c
        ├── boot
        │   ├── config-5.4.39-g0817b280da6c
        │   ├── System.map-5.4.39-g0817b280da6c
        │   └── vmlinuz-5.4.39-g0817b280da6c
        └── lib.tar.gz

3 directories, 4 files
```

Copy it to `EFI-SYSTEM/syslinux/vmlinuz.A`.

By the way, I understand current packaging is a little bit messy. I'll try to improve in my spare time...

**Comment by KenMizz** [comment]
thanks
